name: built_redux
version: 8.0.3+1
description: A state management library written in dart that enforces immutability
homepage: https://github.com/davidmarne/built_redux
dependencies:
  analyzer: '>=5.0.0 <7.0.0'
  build: ">=1.0.0 <6.0.0"
  built_collection: ^5.1.1
  built_value: ^8.6.2
  source_gen: ">=0.9.4 <2.0.0"
  test: ^1.16.0

dev_dependencies:
  build_runner: ^2.4.6
  build_test: ^2.2.0
  built_value_generator: ^8.6.2
  build_web_compilers: ^4.0.5
  workiva_analysis_options: ^1.3.0

environment:
  sdk: ">=2.12.0 <3.0.0"
